// Generated by Resources.swift

import UIKit

// MARK: - UIImage extension

extension UIImage {
    convenience init!(assetName: Images) {
        self.init(named: assetName.rawValue)
    }
}

// MARK: - Images

enum Images: String {
    case chevronRightSmallGray900 = "chevronRightSmallGray900"
    case locationFill = "locationFill"

    var image: UIImage {
        return UIImage(named: self.rawValue)!
    }
}
