// Generated by Resources.swift

// MARK: - String extension

extension String {
    init(localizableName: Strings) {
        self.init(NSLocalizedString(localizableName.rawValue, comment: ""))
    }
}

// MARK: - Strings

enum Strings: String {
    case test = "test"
    case test2 = "test2"
    case test3 = "test3"

    var string: String {
        return String(localizableName: self.rawValue)!
    }
}
